cases = {
    'zero': 'zero',
    '/wp-login.php': 'wplogin.html',
    '/favicon.ico': 'favicon.ico',
    '/searchreplacedb2.php': 'zero',
    '/wp-config.php': 'wpconfig.php',
    '/wp-config.bak': 'wpconfig.php',
    '/wp-config.old': 'wpconfig.php',
    '/wp-config.orig': 'wpconfig.php',
    '/wp-config.original': 'wpconfig.php',
    '/wp-config.php%7E': 'wpconfig.php',
    '/wp-config.php.bak': 'wpconfig.php',
    '/wp-config.php.old': 'wpconfig.php',
    '/wp-config.php.orig': 'wpconfig.php',
    '/wp-config.php.original': 'wpconfig.php',
    '/wp-config.php.save': 'wpconfig.php',
    '/wp-config.php.swo': 'wpconfig.php',
    '/wp-config.php_bak': 'wpconfig.php',
    '/wp-config.php.swp': 'wpconfig.php',
    '/wp-config.save': 'wpconfig.php',
    '/wp-config.txt': 'wpconfig.php',
    '/%23wp-config.php%23': 'wpconfig.php',
}
