#!/usr/bin/env python3
"""Check for documentation drift between docs and code.

Extends basic file-existence checks with:
- Config-parity: reconciles Config dataclass fields with .env.example vars
  and generate_config_file() output (with documented allowlist).
- CLI-flag reachability: asserts every argparse flag is referenced elsewhere
  in the codebase (catches dead flags like --proxy).
"""

from __future__ import annotations

import ast
import os
import re
import sys
from pathlib import Path

errors: list[str] = []


# ── helpers ───────────────────────────────────────────────────────────────────


def _read(path: str) -> str:
    """Read a file, returning empty string if missing."""
    try:
        return Path(path).read_text()
    except FileNotFoundError:
        return ''


def _check_file_exists(path: str) -> None:
    """Add an error if the path doesn't exist."""
    if not os.path.exists(path):
        errors.append(f'{path} does not exist')


# ── Allowlists & mappings (must be defined before checks that use them) ───────

GENERATED_CONFIG_ALLOWLIST: set[str] = {
    # Section header comments / structural markers
    'honeypot',
    'hive',
    'database',
    'security',
    'logging',
    'dump',
    'lockfile',
    'alerting',  # [alerting] section header written by generate_config_file()
    # [alerting] keys written by generate_config_file() — these are TOML
    # section keys consumed by alerting.py via settings.ALERTING, not direct
    # Config dataclass attributes (issue #215).
    'enabled',
    'log_only',
    # [dashboard] section header + keys written by generate_config_file()
    # (issue #234). `secret` is auto-generated (not an env var); the other keys
    # mirror DASHBOARD_* Config fields but are written under [dashboard].
    'dashboard',
    'port',
    'bind',
    'secret',
    'time_range',
    # Derived/compound fields that are documented but not direct Config attrs
    'authorized_bees',  # stored as dict, written as string in config file
}

TOML_TO_CONFIG_FIELD: dict[str, str] = {
    'honeypot.honeyport': 'HONEYPORT',
    'honeypot.honeyfolder': 'HONEYFOLDER',
    'honeypot.port_mode': 'HONEY_PORT_MODE',
    'honeypot.top_ports': 'HONEY_TOP_PORTS',
    'hive.hivehost': 'HIVEHOST',
    'hive.hiveport': 'HIVEPORT',
    'hive.hivelogin': 'HIVELOGIN',
    'hive.hivepass': 'HIVEPASS',
    'database.backend': 'DB_BACKEND',
    'database.path': 'DB_PATH',
    'database.pg_host': 'DB_PG_HOST',
    'database.pg_port': 'DB_PG_PORT',
    'database.pg_db': 'DB_PG_DB',
    'database.pg_user': 'DB_PG_USER',
    'database.pg_password': 'DB_PG_PASSWORD',
    'database.pg_sslmode': 'DB_PG_SSLMODE',
    'database.pg_dsn': 'DB_PG_DSN',
    'security.authorized_bees': 'AUTHORIZED_BEES',
    'security.default_key': 'DEFAULT_KEY',
    'logging.file': 'LOG_FILE',
    'dump.dump_file': 'DUMP_FILE',
    'lockfile.lockfile': 'LOCKFILE',
}

INTENTIONALLY_OMITTED: set[str] = {
    'DB_BACKENDS',  # tuple of allowed backends — internal validation only, not user-configurable
}

ENV_EXAMPLE_ALLOWLIST: set[str] = {
    'DB_BACKENDS',  # not a user-facing env var
    'ALERTING',  # derived dict reconstructed from the [alerting] TOML section, not an env var
    # [dashboard] (issue #234): server-side stats view. DASHBOARD_SECRET is
    # auto-generated by generate-config (not a user-set env var); the other
    # DASHBOARD_* fields are optional and default to safe loopback/off values.
    'DASHBOARD_ENABLED',
    'DASHBOARD_PORT',
    'DASHBOARD_BIND',
    'DASHBOARD_SECRET',
    'DASHBOARD_TIME_RANGE',
}


# ── Check 1: README's directory tree matches reality ─────────────────────────

readme_paths = [
    'manyfaced/mfh.py',
    'manyfaced/common/config.py',
    'manyfaced/server/server.py',
    'manyfaced/client/client.py',
    'test/test_http_handler.py',
    'pyproject.toml',
    'README.md',
]

for path in readme_paths:
    _check_file_exists(path)


# ── Check 2: Config fields documented in CONFIG.md exist in Config dataclass ─

config_file = 'manyfaced/common/config.py'
_check_file_exists(config_file)

if os.path.exists(config_file):
    config_src = _read(config_file)

    # Extract field names from the @dataclass(frozen=True) class Config: block
    try:
        tree = ast.parse(config_src)
        config_fields: set[str] = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == 'Config':
                for item in node.body:
                    if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                        config_fields.add(item.target.id)
    except SyntaxError:
        errors.append('Failed to parse Config dataclass from config.py')


# ── Check 3: Config-parity — reconcile with .env.example ─────────────────────

env_example = '.env.example'
_check_file_exists(env_example)

if os.path.exists(env_example):
    env_src = _read(env_example)
    # Extract HONEY_* variable names, strip prefix → match against Config fields
    env_vars: set[str] = set()
    for line in env_src.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        m = re.match(r'^HONEY_([A-Z_]+)=', line)
        if m:
            # Convert HONEY_DB_PG_HOST → DB_PG_HOST (strip section prefix)
            env_vars.add(m.group(1))

    missing_in_env = config_fields - env_vars - ENV_EXAMPLE_ALLOWLIST
    extra_in_env = env_vars - config_fields
    for f in sorted(missing_in_env):
        errors.append(f'Config field {f} not found in .env.example')
    for v in sorted(extra_in_env):
        errors.append(f'.env.example var HONEY_{v} not a Config dataclass field')


# ── Check 4: generate_config_file() output matches Config fields ─────────────

if os.path.exists(config_file):
    try:
        tree = ast.parse(config_src)
        gen_method_lines: list[str] = []
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == 'Config':
                for item in node.body:
                    if isinstance(item, ast.FunctionDef) and item.name == 'generate_config_file':
                        # Collect all string lines that produce config output:
                        # 1. f-string parts (JoinedStr values)
                        # 2. Plain string constants (e.g., 'authorized_bees = ""')
                        for sub in ast.walk(item):
                            if isinstance(sub, ast.JoinedStr):
                                for val in sub.values:
                                    if isinstance(val, ast.Constant) and isinstance(val.value, str):
                                        gen_method_lines.append(val.value)
                            elif isinstance(sub, ast.Constant) and isinstance(sub.value, str):
                                # Plain string literal used as a config line
                                gen_method_lines.append(sub.value)

        # Extract TOML keys from generated lines (e.g., "honeyport = {self.HONEYPORT}")
        toml_keys: set[str] = set()
        for line in gen_method_lines:
            m = re.match(r'^\s*(\w+)\s*=', line)
            if m:
                toml_keys.add(m.group(1))

        # Check that every TOML key maps to a known Config field or is in the allowlist
        for key in sorted(toml_keys):
            mapped_field = None
            if key in config_fields:
                mapped_field = key
            else:
                for toml_path, field_name in TOML_TO_CONFIG_FIELD.items():
                    section, toml_key = toml_path.split('.', 1)
                    if toml_key == key:
                        mapped_field = field_name
                        break

            if mapped_field is None and key not in GENERATED_CONFIG_ALLOWLIST:
                errors.append(
                    f"generate_config_file() writes '{key}' but it's neither a "
                    f'Config field nor in GENERATED_CONFIG_ALLOWLIST or TOML_TO_CONFIG_FIELD'
                )

        # Check that every Config field appears as a TOML key (or is intentionally omitted)
        for cf in sorted(config_fields):
            if cf in INTENTIONALLY_OMITTED:
                continue  # skip fields that are intentionally not user-configurable
            toml_key = None
            for toml_path, field_name in TOML_TO_CONFIG_FIELD.items():
                if field_name == cf:
                    section, toml_key = toml_path.split('.', 1)
                    break
            if toml_key is not None and toml_key not in toml_keys:
                errors.append(
                    f'Config field {cf} has no corresponding TOML key '
                    f"'{toml_key}' in generate_config_file()"
                )

    except SyntaxError:
        errors.append('Failed to parse generate_config_file() from config.py')


# ── Check 5: CLI flags in arguments.py are documented in README ───────────────

args_file = 'manyfaced/common/arguments.py'
_check_file_exists(args_file)

if os.path.exists(args_file):
    args_src = _read(args_file)

    # Extract --flag patterns, skip --help (auto-generated)
    flags: list[str] = re.findall(r'--([\\w-]+)', args_src)
    flags = [f for f in flags if f != 'help']

    readme_content = _read('README.md')

    for flag in flags:
        # Check if the full flag is documented
        if f'--{flag}' not in readme_content:
            short_form = f'-{flag[0]}'
            if short_form not in readme_content:
                errors.append(f'CLI flag --{flag} in arguments.py not documented in README')


# ── Check 6: CLI-flag reachability — every argparse flag is referenced elsewhere ─

if os.path.exists(args_file):
    try:
        args_tree = ast.parse(args_src)
        arg_flags: set[str] = set()
        for node in ast.walk(args_tree):
            if isinstance(node, ast.Call):
                func = node.func
                if isinstance(func, ast.Attribute) and func.attr == 'add_argument':
                    # Collect all string arguments to add_argument
                    for call_arg in node.args:
                        if isinstance(call_arg, ast.Constant) and isinstance(call_arg.value, str):
                            arg_flags.add(call_arg.value)
    except SyntaxError:
        errors.append('Failed to parse argparse flags from arguments.py')

    # For each flag, check it's referenced elsewhere in the codebase
    for flag in sorted(arg_flags):
        if flag.startswith('-'):
            found = False
            for pyfile in Path('.').rglob('*.py'):
                if pyfile.name == 'arguments.py':
                    continue
                try:
                    content = pyfile.read_text()
                    if flag in content:
                        found = True
                        break
                except (OSError, UnicodeDecodeError):
                    pass
            if not found:
                errors.append(f'argparse flag {flag} defined but never referenced elsewhere')


# ── Check 7: File paths mentioned in README exist ─────────────────────────────

readme_content_full = _read('README.md')
if readme_content_full:
    readme_paths_to_check: set[str] = set()
    for match in re.finditer(
        r"(?:^|[\\s`'\\\",;])((?:manyfaced|test|\\.github)/[\\w./-]+?)(?:[\\s`'\\\",;]|$)",
        readme_content_full,
    ):
        path = match.group(1)
        # Clean up trailing punctuation
        path = path.rstrip('`,;\'"')
        readme_paths_to_check.add(path)

    for path in sorted(readme_paths_to_check):
        _check_file_exists(path)


# ── Check 8: Reverse CLI-flag parity (every README flag exists in arguments.py) ─

if os.path.exists(args_file):
    readme_cli = _read('README.md')
    readme_flags: set[str] = set()
    # Only match flags inside table data cells (lines starting with '|'), never
    # the divider rows (|---|) or prose. A cell looks like: `| -c [PORT] |`.
    for line in readme_cli.splitlines():
        if not line.lstrip().startswith('|'):
            continue
        for m in re.finditer(r'`(-{1,2}[\w-]+)`', line):
            readme_flags.add(m.group(1))

    for flag in sorted(readme_flags):
        if flag not in args_src and flag not in {'--help'}:
            errors.append(
                f'README documents CLI flag {flag} but it is not present in arguments.py '
                f'(stale/removed flag — check #147)'
            )


# ── Check 9: Optional-dependency import reachability ──────────────────────────
# Every distribution in [project.optional-dependencies] should be imported
# somewhere under manyfaced/ (catches phantom deps). Build-only deps are allowlisted.

_OPTIONAL_DEP_BUILD_ONLY: set[str] = {
    'pytest',
    'pytest-cov',
    'basedpyright',
    'ruff',
    'build',
    'twine',
    'pyyaml',  # used only by test_container_build.py, not by manyfaced/ source
}


def _pyproject_optional_deps() -> set[str]:
    """Return the set of optional-dependency distribution names from pyproject.toml."""
    pyproject = _read('pyproject.toml')
    if not pyproject:
        return set()
    block = re.search(r'\[project\.optional-dependencies\](.*?)(\n\[|\Z)', pyproject, re.DOTALL)
    if block:
        deps: set[str] = set()
        # Extract quoted package specs inside the dependency arrays, e.g.
        # postgres = ["psycopg2-binary>=2.9"]  ->  psycopg2-binary
        # The spec may carry version operators (>=, ==, ~=, ...) which are not
        # part of the distribution name, so strip everything from the first
        # non-name character. [\\w.-]+ alone can't span "psycopg2-binary>=2.9".
        for spec in re.findall(r'["\']([^"\']+)["\']', block.group(1)):
            name = re.split(r'[<>=!~ ]', spec.strip(), maxsplit=1)[0].strip()
            if name:
                deps.add(name)
        return deps
    return set()


optional_deps = _pyproject_optional_deps()
# Distribution names don't always match import names. Map the known
# distribution -> import name so the phantom check scans for the right symbol
# (e.g. `psycopg2-binary` is imported as `psycopg2`).
_DIST_TO_IMPORT: dict[str, str] = {
    'psycopg2-binary': 'psycopg2',
    'pyyaml': 'yaml',
}
for dep in sorted(optional_deps):
    if dep in _OPTIONAL_DEP_BUILD_ONLY:
        continue
    import_name = _DIST_TO_IMPORT.get(
        dep,
        dep.split('[')[0].split('>')[0].split('=')[0].split('<')[0].strip(),
    )
    found_import = False
    for pyfile in Path('manyfaced').rglob('*.py'):
        try:
            content = pyfile.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        if re.search(
            rf'^\s*import\s+{re.escape(import_name)}\b', content, re.MULTILINE
        ) or re.search(rf'^\s*from\s+{re.escape(import_name)}\b', content, re.MULTILINE):
            found_import = True
            break
    if not found_import:
        errors.append(
            f'Optional dependency "{dep}" is not imported anywhere under manyfaced/ '
            f'(phantom dependency — check #147)'
        )


# ── Check 10: Curated dead public-API guard ───────────────────────────────────
# Deny-by-default dead-API detection is too noisy for an LLM-maintained codebase
# (utility methods called only by subclasses/handlers look "dead" to a textual
# scan). Instead we keep an explicit CURATED list of known-dead public APIs; the
# check fails if any of them is still defined. Extend this list as real dead code
# is confirmed — that turns a one-off cleanup into a permanent invariant.

_CURATED_DEAD_PUBLIC_APIS: set[str] = {
    # e.g. 'bot_profile.record_interaction',  # (confirmed NOT dead — used by router)
}

for qual in sorted(_CURATED_DEAD_PUBLIC_APIS):
    module_part, _, name_part = qual.rpartition('.')
    found = False
    for pyfile in Path('manyfaced').rglob('*.py'):
        try:
            src = pyfile.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        if re.search(rf'\bdef\s+{re.escape(name_part)}\b', src):
            found = True
            break
    if found:
        errors.append(
            f'Curated dead public API {qual} is still defined (should have been removed — check #147)'
        )


# ── Check 11: No-legacy-shims policy (grep guard) ─────────────────────────────
# Flag *shim* markers (explicit backward-compat wrappers) in code so they get
# conscious review instead of silently accumulating. The bare words "legacy" /
# "backward compat" appear in legitimate design comments and are NOT flagged;
# only explicit shim wrappers are. Docs are exempt (code only).

_SHIM_MARKERS: list[str] = [
    'deprecated shim',
    'compat shim',
    'backward-compat shim',
    'backwards-compat shim',
    'legacy shim',
]


def _legacy_shim_scan() -> None:
    for pyfile in sorted(Path('manyfaced').rglob('*.py')):
        try:
            src = pyfile.read_text()
        except (OSError, UnicodeDecodeError):
            continue
        low = src.lower()
        for marker in _SHIM_MARKERS:
            if marker in low:
                errors.append(
                    f'Legacy shim marker "{marker}" found in {pyfile} '
                    f'(no-legacy-shims policy — check #147; remove or get conscious review)'
                )


_legacy_shim_scan()


# ── Report ────────────────────────────────────────────────────────────────────

if errors:
    print('Documentation drift detected:')
    for error in errors:
        print(f'  - {error}')
    sys.exit(1)
else:
    print('No documentation drift detected')
    sys.exit(0)
